parameters:
    guzzle.client.class: Guzzle\Service\Client
    guzzle.service_description.class: Guzzle\Service\Description\ServiceDescription
    guzzle.listener.command_listener.class: Xamado\GuzzleBundle\Service\Command\CommandListener
    guzzle.response_parser.serializer.class: Xamado\GuzzleBundle\Service\Command\SerializerResponseParser
    guzzle.data_collector.requests_collector.class: Xamado\GuzzleBundle\DataCollector\GuzzleDataCollector

services:
    guzzle.client.abstract:
        class: %guzzle.client.class%
        abstract: true
        tags:
            - { name: guzzle.client }
        calls:
            - [ addSubscriber, [ @guzzle.listener.command_listener ]]

    guzzle.service_description.abstract:
        class: %guzzle.service_description.class%
        abstract: true
        factory_class: %guzzle.service_description.class%
        factory_method: factory

    guzzle.response_parser.serializer:
        class: %guzzle.response_parser.serializer.class%
        arguments:
            - @serializer

    guzzle.listener.command_listener:
        class: %guzzle.listener.command_listener.class%
        arguments:
            - @guzzle.response_parser.serializer

    guzzle.data_collector.requests_collector:
        class: %guzzle.data_collector.requests_collector.class%
        tags:
            - { name: data_collector, template: "XamadoGuzzleBundle:Profiler:layout", id: "requests_collector" }