parameters:
    guzzle.client.class: Guzzle\Service\Client
    guzzle.service_description.class: Guzzle\Service\Description\ServiceDescription
    guzzle.listener.command_listener.class: Xamado\GuzzleBundle\Service\Command\CommandListener
    guzzle.response_parser.serializer.class: Xamado\GuzzleBundle\Service\Command\SerializerResponseParser

services:
    guzzle.response_parser.serializer:
        class: %guzzle.response_parser.serializer.class%

    guzzle.listener.command_listener:
        class: %guzzle.listener.command_listener.class%
        arguments:
            - @guzzle.response_parser.serializer